name: Deploy dumstigram to heroku.

on:
  push:
    branches: [master]
    paths:
      - 'Dumstigram/Api/*'
      - 'Dumstigram/Infra/*'

jobs:
  deployBackend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release Dumstigram Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./Dumstigram
          dockerfile_name: Infra/Dockerfile.web
          process_type: web
